name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        ssh-key: ${{ secrets.PRIVATE_SSH_KEY }}
        repository: mattbillenstein/aoc-input
        path: aoc-input

    - uses: actions/checkout@v4
      with:
        path: aoc

    - name: Install dependencies
      run: |
        cd aoc
        sudo apt-get update
        sudo apt-get install pypy3 python3 rustc libsdl2-dev
        make install

    - name: Run
      run: |
        cd aoc
        make check
