name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ssh-key: ${{ secrets.PRIVATE_SSH_KEY }}
        repository: mattbillenstein/aoc-input

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install pypy3 python3
        make install

    - name: Run
      run: |
        make check
